exynos: mmc: Provide proper buffer boundaries for dcache invalidation
After dcache was enabled, the following messages started showing up on
u-boot console at startup:

ERROR: v7_dcache_inval_range - stop address is not aligned - 0xff917a88

The problem is with the exynos mmc driver: at certain points it
allocates buffers which are smaller than the cache line size.

With the recent upgrade of include/common.h the automatic cache line
aligned buffers are guaranteed to be padded to the closest cache line
boundary, so it is safe to pass the rounded up buffer end address to
dcach invalidating function.

BUG=chrome-os-partner:18329
TEST=manual

   . built and booted peach. No more cache alignment errors are being
     reported. The MMC driver still works (successfully booted from
     the SD card).

Change-Id: I51d5544ba61858dc232452032e83fb1f44616c13
Signed-off-by: Vadim Bendebury <vbendeb@chromium.org>
Reviewed-on: https://gerrit-int.chromium.org/38722
Reviewed-by: Vadim Bendebury <vbendeb@google.com>
Tested-by: Vadim Bendebury <vbendeb@google.com>
Commit-Queue: Vadim Bendebury <vbendeb@google.com>