exynos: provide placeholder printf for SPL
The SPL configuration does not include support for libcommon, which provides
printf, meaning that any function that calls printf (such as get_pll_clk on
error) will fail to link into SPL with an undefined reference to printf.

Provide a stub printf to allow such functions to successfully link.

BUG=none
BRANCH=none
TEST=manual.  Successfully build SPL with a call to get_pll_clk().

Change-Id: Ie135fd1c031fa11d64978b94cec53074d1d38f2b
Signed-off-by: Michael Pratt <mpratt@chromium.org>
Reviewed-on: https://gerrit.chromium.org/gerrit/61204
Reviewed-by: Vincent Palatin <vpalatin@chromium.org>